steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', '${_REGION_N_}-docker.pkg.dev/${PROJECT_ID}/${_REPO_N_}/${_IMAGE_N_}:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: push
  waitFor: 
    - build
  args: ['push', '${_REGION_N_}-docker.pkg.dev/${PROJECT_ID}/${_REPO_N_}/${_IMAGE_N_}:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  waitFor:
    - build 
    - push
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_IMAGE_N_}'
    - '--image=${_REGION_N_}-docker.pkg.dev/${PROJECT_ID}/${_REPO_N_}/${_IMAGE_N_}:latest'
    - '--region=${_REGION_N_}'
    - '--concurrency=100'
    - '--set-env-vars=ENV=prod,NODE_ENV=production'
    - '--allow-unauthenticated'
    - '--project=${PROJECT_ID}'
    - '--no-cpu-boost'
    - '--network=${_NETWORK_N_}'
    - '--subnet=${_SUBNET_N_}'
    - '--platform=managed'


options:
  logging: CLOUD_LOGGING_ONLY