steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/${PROJECT_ID}/my-first-repo', '.']
- name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'europe-west4-docker.pkg.dev/${PROJECT_ID}/my-first-repo']
